
[functions.create-momo-payment]
enabled = true
verify_jwt = true
import_map = "./functions/create-momo-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-momo-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-momo-payment/*.html" ]

[functions.momo-ipn-handler]
enabled = true
verify_jwt = true
import_map = "./functions/momo-ipn-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/momo-ipn-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/momo-ipn-handler/*.html" ]
